### PR TITLE
Show "come back later" message on join early

### PR DESCRIPTION
**Pull request by neoformit**
Resolves https://github.com/galaxyproject/tiaas2/issues/28, but see my comment there regarding timezones.

When a user tries to join before the `training.start` date:

image

I also restyled `error.html` to be centered with larger font (to match above) so it looks a little nicer:

image

### CODE REVIEW

**Comment by hexylena** [comment]
We should probably transition these to time + TZ aware, but that'd still be difficult for multi-country events and it complicates the form a bit.

We could just do a -1 day from the start? 

(yay bigger fonts!)

**Comment by neoformit** [comment]
> We could just do a -1 day from the start?

Would you always expect Galaxy EU TIaaS events to be in CET? If so, we could just show the server timezone (`settings.TIME_ZONE`) in the form, so applicants know the timezone applied to their suggested dates?

Then we just need to make sure admins set a `TIME_ZONE`.

**Comment by hexylena** [comment]
> Would you always expect Galaxy EU TIaaS events to be in CET +/- 2 hours? If so, we could just show the server timezone (settings.TIME_ZONE) in the form, so applicants know the timezone applied to their suggested dates?

This seems *likely*, but I guess during Smörgåsbord we were the EMEA provider, which means there were people joining up to 5h early (and more if anyone from APAC decided to join eu due to e.g. missing tools.)

I guess that's probably the worst case scenario: tools only on UseGalaxy.org (or EU), a global event, and someone from auckland needing EU for a specific tutorial that they want to follow at 19 kiwi time, and they can't join the training yet.

I don't think it's a *likely* scenario, but I think the outcome is unpleasant for the user.

From the admin side, unless you've written a job rule with no fallback (EU falls back, ORG doesn't allocate separate resources, AU I think the training cluster always exists), then it's fine for someone to be "early" to a training.

The training message's main benefit is really just helping participants know to check their calendar/event information if they're seeing this.

**Comment by hexylena** [comment]
Could I trouble you to add a corresponding "late" route/page? I think that would be useful for similar reasons, especially during smörgåsbord.

**Comment by neoformit** [comment]
> Could I trouble you to add a corresponding "late" route/page? I think that would be useful for similar reasons, especially during smörgåsbord.

Already added that in the big TIaaS 2.1 merge:
https://github.com/galaxyproject/tiaas2/blob/c42ee69058422318614e585a0dd1e87a2f55fe82/training/views.py#L286-L300

**Comment by neoformit** [comment]
> This seems likely, but I guess during Smörgåsbord we were the EMEA provider, which means there were people joining up to 5h early (and more if anyone from APAC decided to join eu due to e.g. missing tools.)

How about we do your +1 day fix for now, and if we want a better long term solution we can just post a tracking issue for a `Training.timezone` field? I may find time to add that at some stage.

- [ ] Add +1 day allowance to "early" handler
- [ ] Add +1 day allowance to "late" handler
- [ ] Post issue requesting timezone support

**Comment by hexylena** [comment]
> Already added that in the big TIaaS 2.1 merge.

oh, wow, completely forgot that already, cheers.

> How about we do your +1 day fix for now, and if we want a better long term solution we can just post a tracking issue for a Training.timezone field? I may find time to add that at some stage.

that sounds good for now!

I'm still a little wary given that:
- timezones are hard, even for us actively thinking about edge cases.
- instructors will basically certainly _not_ be thinking about edge cases like we are.
but maybe you'll find some way to work around the communication to instructor issue, and then it'll be fine :) 

but yes, let's add -1/+1 day on the ends and call it a day.

**Comment by neoformit** [comment]
> but yes, let's add -1/+1 day on the ends and call it a day

Just a thought, what if we go +/-9 hours? Then an AU session can still run on the US server (the most extreme case) from 8am?

> I'm still a little wary

Yep I don't think it's something to rush into, and our temporary fix is pretty acceptable anyway (I think).

**Review by hexylena — APPROVED** [review]

**Pull request merged**
