### PR TITLE
Tiaas 2.1

### PR DESCRIPTION
**Pull request by neoformit**
# Significant upgrades to TIaaS2

_**Merge the Ansible role PR before this!**_

For deployment instructions, see the new [Ansible role README.md](https://github.com/neoformit/ansible-tiaas2/blob/tiaas-2.1/README.md)

### Enhancements

- Templatable content (custom footer / HTML snippets - see `./templates`)
- De-europize everywhere
- New interactive calendar (admins can see event details)
- Re-design form and landing page
- Styling updates on minor pages (thanks, error etc)
- Create `TrainingFactory` to populate dev/test DB
- New settings vars to hide advertising/GDPR statement
- Navbar for site navigation

### Bug fixes

- Correct backend code presenting user stats (don't count events that haven't occurred yet)
- Don't allow users to join events that have already finished (creates admin burden as new group is created again and has to be closed)
- Fix pages that break when DB is empty
- Strip HTML content from plain text email

### General refactoring (sorry)

- Refactor some `views.py` Django code for efficiency
- `base.html` template refactored to include head and script blocks
- Remove wildcard `ALLOWED_HOSTS` - set explicitly
- Non-sensitive settings vars injected into global template context
- Expect `TIAAS_DOMAIN` to be a domain, not a URL
- Change `TIAAS_DOMAIN` to `GALAXY_DOMAIN`

### CODE REVIEW

**Comment by hexylena** [comment]
Is there any way we can replace vendor with pulling those during build time or so? I hate to involve npm but, can we do that? It's going to make search essentially *useless* on this repository.

**Comment by neoformit** [comment]
Yeah I admit they are really annoying to diff. I'd prefer a fix that without npm if possible.

For search my editor allows something equivalent to `grep -v vendor` so I haven't found search to be an issue - depends how you do it I guess.

For the diff - I'd like to try this option and see if it helps:

https://stackoverflow.com/a/58923410/9739282
image

**Comment by neoformit** [comment]
Ok that totally doesn't work! I've just moved fontawesome to a load from a CDN - it loads very fast so probably better than local serve anyway. That's all that was clogging up the diff so should be fine now? (I kept `material-icons.css` as I experienced weird slow loading from CDN before, and it's just one file).

**Comment by hexylena** [comment]
I've changed the base to 'main2', to let us (at least for a time) separate the branches while people upgrade for safety.

Maybe at some point in the future we merge that back / go back to main as default.

**Pull request merged**
